import fs from 'node:fs';
fs.mkdirSync('compositions/frames',{recursive:true});
const font=`@font-face{font-family:'Bricolage Grotesque';src:url('assets/fonts/captured-3y9K6as8bTXq_nANBjzKo3IeZx8z6up5BeSl9D4dj_x9PpZBMlGIInHWVyNJ.woff2') format('woff2');font-weight:400 800;font-style:normal;font-display:block} @font-face{font-family:'Instrument Sans';src:url('assets/fonts/captured-pxiTypc9vsFDm051Uf6KVwgkfoSxQ0GsQv8ToedPibnr0SZe1ZuWi3g.woff2') format('woff2');font-weight:400 700;font-style:normal;font-display:block}`;
const common=`${font}
*{box-sizing:border-box}#root{position:absolute;inset:0;width:100%;height:100%;overflow:hidden;color:#18181a;font-family:'Bricolage Grotesque',sans-serif;--paper:#f3f0e7;--ink:#18181a;--lime:#c8f25a;--sky:#a9d8ff;--amber:#f5c451;--violet:#cbb6ff}
.clip{position:absolute;inset:0}.eyebrow{font-family:'Instrument Sans',sans-serif;font-size:24px;font-weight:700;letter-spacing:4px;text-transform:uppercase}.brand-mini{position:absolute;left:88px;top:54px;display:flex;align-items:center;gap:12px;font-size:29px;font-weight:800}.brand-mini img{width:48px;height:48px}.chapter{position:absolute;right:88px;top:70px;font-size:20px;letter-spacing:3px;font-family:'Instrument Sans',sans-serif;font-weight:700}.pill{border:3px solid #18181a;border-radius:999px;padding:16px 28px;font-size:26px;font-weight:700;background:#fffdf7;box-shadow:5px 5px 0 #18181a}.folder-icon{position:relative;width:66px;height:48px;border:3px solid #18181a;border-radius:7px;background:var(--amber)}.folder-icon:before{content:'';position:absolute;top:-14px;left:-3px;width:31px;height:16px;border:3px solid #18181a;border-bottom:0;border-radius:7px 7px 0 0;background:inherit}.rule{position:absolute;left:88px;right:88px;top:125px;height:2px;background:currentColor;opacity:.2}h1,h2,p{margin:0}.card{border:3px solid #18181a;border-radius:26px;box-shadow:8px 8px 0 #18181a;background:#fffdf7}.small{font-family:'Instrument Sans',sans-serif;font-size:25px;line-height:1.45}
`;
const brand=(chapter)=>`<div class="brand-mini"><img src="assets/logo.svg" alt="Tidymark logo"><span>Tidymark</span></div><div class="chapter">${chapter}</div><div class="rule"></div>`;
const pop=(sel,t,d=.6)=>`tl.fromTo('${sel}',{scale:.88,opacity:0,y:24},{scale:1,opacity:1,y:0,duration:${d},ease:'back.out(1.35)'},${t});`;
const rise=(sel,t,d=.65)=>`tl.fromTo('${sel}',{y:65,opacity:0},{y:0,opacity:1,duration:${d},ease:'power3.out'},${t});`;
function scene(id,d,bg,css,html,js){fs.writeFileSync(`compositions/frames/${id}.html`,`<template>\n<style>${common}\n${css}</style>\n<div id="root" data-composition-id="${id}" data-width="1920" data-height="1080" data-duration="${d}"><div class="clip" data-start="0" data-duration="${d}" data-track-index="0" style="background:${bg}"></div>${html}</div>\n<script src="assets/gsap.min.js"></script><script>(function(){const tl=gsap.timeline({paused:true});${js}window.__timelines['${id}']=tl;})();</script>\n</template>`);}
const labels=['Weeknight lasagna','3 days in Lisbon','Running shoes','Kitchen remodel','One-bowl banana bread','That article…'];
const colors=['#f5c451','#c8f25a','#a9d8ff','#cbb6ff','#f5c451','#a9d8ff'];
const coords=[[110,190, -9],[1320,205,8],[70,705,5],[1360,690,-7],[270,865,-5],[1140,870,6]];
const cards=labels.map((x,i)=>`<div id="s1-card${i}" class="s1-book card" style="left:${coords[i][0]}px;top:${coords[i][1]}px;background:${colors[i]}"><span class="s1-bookmark" aria-hidden="true"></span><span>${x}</span></div>`).join('');
scene('01-later',6,'#f3f0e7',`
.s1-main{position:absolute;left:410px;top:292px;width:1100px;text-align:center;z-index:3}.s1-line{font-size:139px;line-height:1.05;font-weight:800;letter-spacing:-7px}.s1-highlight{display:inline-block;background:#c8f25a;padding:0 34px 12px;border:3px solid #18181a;border-radius:25px;box-shadow:8px 8px 0 #18181a;margin-top:22px}.s1-question{position:absolute;top:670px;left:520px;width:880px;text-align:center;font-size:63px;font-weight:800;letter-spacing:-2px}.s1-book{position:absolute;width:445px;min-height:104px;padding:28px 25px;display:flex;gap:20px;align-items:center;font-size:28px;font-weight:700}.s1-bookmark{display:block;flex-shrink:0;width:23px;height:33px;background:#18181a;clip-path:polygon(0 0,100% 0,100% 100%,50% 73%,0 100%)}.s1-sub{position:absolute;top:218px;left:620px;width:680px;text-align:center}.s1-dot{position:absolute;width:22px;height:22px;border:3px solid #18181a;border-radius:50%;background:#cbb6ff}
`,`${brand('01 / THE “LATER” PILE')}<div class="s1-sub eyebrow">Sound familiar?</div>${cards}<div class="s1-main"><div id="s1-saved" class="s1-line">Saved</div><div id="s1-later" class="s1-line s1-highlight">for later.</div></div><div id="s1-question" class="s1-question">Now where is it?</div>`,
`${rise('#s1-saved',0,.6)}${pop('#s1-later',.5,.65)}${rise('#s1-question',4,.7)}${labels.map((_,i)=>`tl.fromTo('#s1-card${i}',{y:${i%2?-170:170},x:${i%2?130:-130},rotation:${coords[i][2]*3},opacity:0},{y:0,x:0,rotation:${coords[i][2]},opacity:1,duration:.65,ease:'back.out(1.2)'},${1.5+i*.5});`).join('')}tl.to('#s1-later',{rotation:-2,duration:.18,ease:'power2.inOut'},4.5);tl.to('#s1-later',{rotation:0,duration:.28,ease:'power2.out'},4.68);`);
scene('02-meet',4,'#c8f25a',`
.s2-lock{position:absolute;left:265px;top:200px;display:flex;align-items:center;gap:40px}.s2-logo{width:235px;height:235px}.s2-word{font-size:184px;font-weight:800;letter-spacing:-10px}.s2-tag{position:absolute;top:490px;width:100%;text-align:center;font-size:49px;font-weight:700;letter-spacing:-1.5px}.s2-folders{position:absolute;left:290px;top:660px;display:flex;gap:38px}.s2-folder{width:420px;height:175px;display:flex;align-items:center;justify-content:center;gap:25px;font-size:36px;font-weight:800}.s2-mini{position:absolute;top:94px;width:100%;text-align:center}.s2-tick{position:absolute;bottom:94px;left:760px;width:400px;text-align:center;font-size:27px;font-weight:700}
`,`<div class="s2-mini eyebrow">Meet your bookmark's happy place</div><div id="s2-lock" class="s2-lock"><img class="s2-logo" src="assets/logo.svg" alt="Tidymark"><h1 class="s2-word">Tidymark</h1></div><p id="s2-tag" class="s2-tag">A happy home for every bookmark.</p><div class="s2-folders">${['Recipes','Travel','Good ideas'].map((x,i)=>`<div id="s2-folder${i}" class="s2-folder card" style="background:${['#f5c451','#a9d8ff','#cbb6ff'][i]}"><span class="folder-icon" style="background:inherit"></span>${x}</div>`).join('')}</div><div id="s2-tick" class="s2-tick">Save it. Find it. Enjoy it.</div>`,
`${pop('#s2-lock',0,.75)}${rise('#s2-tag',.7)}${[0,1,2].map(i=>pop('#s2-folder'+i,1.5+i*.5)).join('')}${rise('#s2-tick',3,.5)}`);
const titles=[['One click.','Right folder.','Your best matches, ready to save.'],['Your folders.','Better matches.','Works with the structure you already love.'],['No fit?','Make room.','A new folder, when you need one.']];
scene('03-save',8,'#f3f0e7',`
.s3-copy{position:absolute;left:110px;top:285px;width:800px}.s3-title{font-size:108px;line-height:1.02;font-weight:800;letter-spacing:-5px}.s3-title span{display:block}.s3-title span:last-child{margin-top:15px}.s3-body{margin-top:37px;width:650px;font-family:'Instrument Sans',sans-serif;font-size:32px;line-height:1.5}.s3-shot{position:absolute;left:1040px;top:210px;width:650px;max-height:710px;border-radius:30px;box-shadow:13px 13px 0 #18181a;border:3px solid #18181a}.s3-bg{position:absolute;left:985px;top:172px;width:760px;height:770px;border-radius:55px;background:#a9d8ff;border:3px solid #18181a}.s3-tag{position:absolute;left:112px;top:710px;font-size:24px}.s3-cursor{position:absolute;width:63px;height:80px;left:1530px;top:790px;z-index:8}.s3-note{position:absolute;left:110px;top:860px;font-size:21px;color:#5c5850}.s3-progress{position:absolute;left:110px;top:800px;display:flex;gap:14px}.s3-pip{width:86px;height:9px;background:#dcd7c9;border-radius:9px}
`,`${brand('02 / SAVE THE PAGE')}<div class="s3-bg"></div>${titles.map((lines,i)=>`<div id="s3-copy${i}" class="s3-copy"><h2 class="s3-title"><span>${lines[0]}</span><span>${lines[1]}</span></h2><p class="s3-body">${lines[2]}</p></div><img id="s3-shot${i}" class="s3-shot" src="assets/ui/popup-${i}.png" alt="Actual Tidymark website popup example ${i+1}">`).join('')}<div class="s3-tag pill">One page. A place that fits.</div><div class="s3-progress">${[0,1,2].map(i=>`<div id="s3-pip${i}" class="s3-pip"></div>`).join('')}</div><p class="s3-note small">Actual website examples · illustrative recommendations</p><svg id="s3-cursor" class="s3-cursor" viewBox="0 0 60 80" aria-hidden="true"><path d="M4 4L48 42L29 44L40 68L29 74L17 49L4 63Z" fill="#fffdf7" stroke="#18181a" stroke-width="4" stroke-linejoin="round"/></svg>`,
`${[0,1,2].map(i=>{let t=i*2.5;return `${rise('#s3-copy'+i,t,.55)}tl.fromTo('#s3-shot${i}',{x:140,opacity:0,rotation:4},{x:0,opacity:1,rotation:0,duration:.65,ease:'power3.out'},${t});tl.set('#s3-pip${i}',{backgroundColor:'#18181a'},${t});${i<2?`tl.to(['#s3-copy${i}','#s3-shot${i}'],{opacity:0,x:-100,duration:.2,ease:'power2.in'},${t+2.3});`:''}`;}).join('')}${rise('.s3-tag',1,.5)}tl.fromTo('#s3-cursor',{x:100,y:80,opacity:0},{x:0,y:0,opacity:1,duration:.6,ease:'power3.out'},1.25);${[2,4.5,7].map(t=>`tl.to('#s3-cursor',{scale:.84,duration:.09},${t});tl.to('#s3-cursor',{scale:1,duration:.18,ease:'back.out(1.4)'},${t+.09});`).join('')}`);
const modeNames=['New folders','Your folders','By usage','By project'];
scene('04-ways',10,'#f3f0e7',`
.s4-heading{position:absolute;top:180px;left:90px;font-size:86px;font-weight:800;letter-spacing:-4px}.s4-stage{position:absolute;left:90px;top:310px;width:1196px;height:580px;border:3px solid #18181a;border-radius:28px;background:#fffdf7;box-shadow:10px 10px 0 #18181a}.s4-tabs{position:absolute;left:1340px;top:315px;width:490px;display:flex;flex-direction:column;gap:22px}.s4-tab{position:relative;display:flex;align-items:center;gap:24px;border:3px solid #18181a;border-radius:22px;padding:22px 22px;height:119px;background:#fffdf7;font-size:34px;font-weight:800}.s4-letter{border:2px solid #18181a;display:grid;place-items:center;width:55px;height:55px;border-radius:12px;font-size:33px}.s4-foot{position:absolute;left:97px;top:935px;font-size:24px;color:#5c5850}.s4-count{position:absolute;right:100px;top:198px;font-size:28px;font-weight:700}.s4-caption{position:absolute;left:107px;top:274px;font-size:20px;letter-spacing:2px}
`,`${brand('03 / TIDY THE WHOLE PILE')}<h2 id="s4-heading" class="s4-heading">Four ways. Your kind of tidy.</h2><div class="s4-stage"></div><div class="s4-tabs">${modeNames.map((x,i)=>`<div id="s4-tab${i}" class="s4-tab"><span class="s4-letter" style="background:${['#c8f25a','#a9d8ff','#f5c451','#cbb6ff'][i]}">${'ABCD'[i]}</span><span>${x}</span></div>`).join('')}</div><p class="s4-foot small">Real Tidymark demos · choose what works for you</p>${['a','b','c','d'].map((m,i)=>`<video id="s4-video${i}" class="clip" src="capture/assets/videos/mode-${m}-en.mp4" muted playsinline data-frame-video="approved" data-start="${i*2.5}" data-duration="2.5" data-media-start="0.7" data-track-index="2" data-frame-video-x="108" data-frame-video-y="328" data-frame-video-width="1160" data-frame-video-height="544" data-frame-video-fit="contain"></video>`).join('')}`,
`${rise('#s4-heading',0,.55)}${[0,1,2,3].map(i=>`tl.to('#s4-tab${i}',{backgroundColor:'${['#c8f25a','#a9d8ff','#f5c451','#cbb6ff'][i]}',x:-12,duration:.25,ease:'power2.out'},${i*2.5});${i<3?`tl.to('#s4-tab${i}',{backgroundColor:'#fffdf7',x:0,duration:.2},${i*2.5+2.4});`:''}`).join('')}`);
scene('05-control',6,'#18181a',`
.s5-heading{position:absolute;left:110px;top:200px;width:1700px;text-align:center;font-size:104px;line-height:1.08;font-weight:800;letter-spacing:-5px;color:#f3f0e7}.s5-heading span{color:#c8f25a}.s5-plan{position:absolute;left:425px;top:375px;width:1070px;border-radius:24px;border:2px solid #5c5850;padding:25px;background:#242422}.s5-plan img{display:block;width:100%;border-radius:16px}.s5-chips{position:absolute;top:825px;left:345px;width:1230px;display:flex;justify-content:center;gap:32px}.s5-chip{padding:18px 28px;border:2px solid #f3f0e7;border-radius:99px;font-size:28px;font-weight:700;color:#f3f0e7}.s5-chip:last-child{background:#c8f25a;color:#18181a;border-color:#c8f25a}.brand-mini,.chapter,.rule{color:#f3f0e7}.s5-mark{position:absolute;left:166px;top:510px;width:170px;height:170px;display:grid;place-items:center;border:3px solid #c8f25a;border-radius:50%;font-size:90px;color:#c8f25a}.s5-undo{position:absolute;right:158px;top:510px;width:170px;height:170px;display:grid;place-items:center;border:3px solid #cbb6ff;border-radius:50%;font-size:90px;color:#cbb6ff}
`,`${brand('04 / YOU’RE IN CONTROL')}<h2 id="s5-title" class="s5-heading">Your bookmarks. <span>Your call.</span></h2><div id="s5-plan" class="s5-plan"><img src="assets/ui/plan.png" alt="Actual website move plan with Apply and Undo controls"></div><div id="s5-check" class="s5-mark">✓</div><div id="s5-undo" class="s5-undo">↶</div><div class="s5-chips"><div id="s5-chip0" class="s5-chip">Preview first</div><div id="s5-chip1" class="s5-chip">Apply when ready</div><div id="s5-chip2" class="s5-chip">Undo the last tidy</div></div>`,
`${rise('#s5-title',0,.55)}${rise('#s5-plan',.6,.65)}${pop('#s5-check',2)}${[0,1,2].map(i=>rise('#s5-chip'+i,2+i,.5)).join('')}${pop('#s5-undo',4)}tl.fromTo('#s5-undo',{rotation:-70},{rotation:0,duration:.6,ease:'power3.out'},4);`);
const confetti=Array.from({length:32},(_,i)=>`<i class="s6-particle" style="background:${colors[i%colors.length]};left:${i%2?1610:280}px;top:480px" data-layout-ignore></i>`).join('');
scene('06-finale',6,'#f3f0e7',`
.s6-lock{position:absolute;top:142px;left:502px;display:flex;align-items:center;gap:25px}.s6-logo{width:145px;height:145px}.s6-name{font-size:130px;font-weight:800;letter-spacing:-7px}.s6-title{position:absolute;left:220px;top:370px;width:1480px;text-align:center;font-size:115px;line-height:1.08;font-weight:800;letter-spacing:-5px}.s6-title span{display:block}.s6-more{color:#18181a}.s6-cta{position:absolute;left:728px;top:690px;width:464px;text-align:center;background:#c8f25a;font-size:38px;padding:22px 28px;box-shadow:7px 7px 0 #18181a}.s6-url{position:absolute;top:818px;width:100%;text-align:center;font-size:39px;font-weight:700;letter-spacing:-1px}.s6-foot{position:absolute;top:920px;width:100%;text-align:center;font-size:22px;color:#5c5850}.s6-particle{position:absolute;width:17px;height:30px;border:2px solid #18181a;border-radius:4px;z-index:0}.s6-lock,.s6-title,.s6-cta,.s6-url{z-index:2}
`,`${confetti}<div id="s6-lock" class="s6-lock"><img class="s6-logo" src="assets/logo.svg" alt="Tidymark logo"><h1 class="s6-name">Tidymark</h1></div><div class="s6-title"><span id="s6-less">Less searching.</span><span id="s6-more" class="s6-more">More discovering.</span></div><div id="s6-cta" class="s6-cta pill">Add to Chrome ↗</div><p id="s6-url" class="s6-url">tidy.tmtt.link</p><p class="s6-foot small">For everything you saved for “later.”</p>`,
`${pop('#s6-lock',0,.65)}${rise('#s6-less',.5,.6)}${rise('#s6-more',1.25,.6)}${pop('#s6-cta',2.4,.6)}${rise('#s6-url',3,.5)}
// Seeded index-based burst adapted from the installed confetti registry component.
const particles=gsap.utils.toArray('.s6-particle');particles.forEach((el,i)=>{const dir=i%2?-1:1;tl.fromTo(el,{opacity:0,x:0,y:0,rotation:0},{opacity:1,x:dir*(70+(i*43)%280),y:-150-(i*29)%290,rotation:180+i*37,duration:.8,ease:'power2.out'},.25+i*.007);tl.to(el,{y:400+(i*23)%250,x:dir*(150+(i*43)%330),rotation:360+i*39,opacity:0,duration:2.1,ease:'power2.in'},1.05+i*.007);});`);
// No guessed keyframe promises: these check semantic title arrival and the CTA.
fs.writeFileSync('compositions/frames/06-finale.motion.json',JSON.stringify({duration:6,assertions:[{kind:'appearsBy',selector:'#s6-lock',bySec:.7},{kind:'appearsBy',selector:'#s6-url',bySec:3.6}]},null,2));
let sb=fs.readFileSync('STORYBOARD.md','utf8').replaceAll('status: outline','status: animated');fs.writeFileSync('STORYBOARD.md',sb);
console.log('Six frame compositions authored.');
